language: python
sudo: false
cache: pip

language: python


python:
  # For branches <= 10.0, put `- "2.7.13"`
  - "3.6"
  install:
  
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
